Add ValueCurves from PowerSystems to infrasys
NREL/infrasys pull request #38
Opened 2024-07-09 00:25 UTC by jerrypotts

- Added classes for InputOutputCurve, IncrementalCurve, and AverageRateCurve that call function_data classes to build generic cost curves. These classes are analogous to the structs found in [PowerSystems](https://github.com/NREL-Sienna/PowerSystems.jl/blob/9e6f8a7e073ef7b606d3bc3a32640fcb69789a99/src/models/cost_functions/ValueCurves.jl)
- Added functions to convert between the different value_curves classes (ex: InputOutputToIncremental creates an IncrementalCurve from an existing InputOutputCurve)
- Added functions to function_data to perform calculations for value_curve conversion
- Added additional serialization tests to test_function_data

2024-08-05 18:08 UTC, daniel-thom reviewed
I made a cursory pass and have two minor comments.

2024-08-05 18:46 UTC, pesap commented on src/infrasys/exceptions.py
> +class ISMethodError(ISBaseException):
Yeah, we can use that instead.

2024-08-05 18:58 UTC, pesap commented on src/infrasys/function_data.py
> +        raise ValueError(f"Piecewise x-coordinates must be ascending, got {x_coords}.")
We missed this on the `pyproject.toml`. The updated version include it and make it compliant.

2024-08-13 18:29 UTC, pesap requested changes
LGTM. If you address the changes we can merge it right away.

2024-08-13 18:29 UTC, pesap commented on src/infrasys/production_variable_cost_curve.py
Can we call this file`cost_curves.py` instead?

2024-08-13 18:29 UTC, pesap commented on src/infrasys/production_variable_cost_curve.py
> +    of a Value Curve that may represent input-output, incremental, or average rate
Can we follow numpy style here? First sentence the summary of the class.

2024-08-13 18:29 UTC, pesap commented on src/infrasys/production_variable_cost_curve.py
> +    """
Same numpy style

2024-08-13 18:29 UTC, pesap commented on src/infrasys/value_curves.py
> +        if isinstance(self.function_data, LinearFunctionData):
Can you use match/case statement instead?

2024-08-13 18:29 UTC, pesap commented on tests/test_production_variable_cost_curve.py
Rename according to new file name `test_cost_curves`

2024-08-15 19:13 UTC, merged